import re
import unicodedata

from seuxpc.config.constants import CULTURAL_DIMENSIONS


def _normalize_key(value):
    if value is None:
        return ""

    text = str(value).strip().lower()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    return re.sub(r"[^a-z0-9]+", "", text)


HOFSTEDE = {'AFE': {'DP': 0.64,
         'EI': 0.52,
         'IND': 0.27,
         'LCS': 0.4,
         'OGI': 0.41,
         'OLP': 0.32,
         'country': 'Africa East',
         'country_code': 'AFE'},
 'AFW': {'DP': 0.77,
         'EI': 0.54,
         'IND': 0.2,
         'LCS': 0.78,
         'OGI': 0.46,
         'OLP': 0.09,
         'country': 'Africa West',
         'country_code': 'AFW'},
 'ALB': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.15,
         'OGI': None,
         'OLP': 0.61,
         'country': 'Albania',
         'country_code': 'ALB'},
 'ALG': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.32,
         'OGI': None,
         'OLP': 0.26,
         'country': 'Algeria',
         'country_code': 'ALG'},
 'AND': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.65,
         'OGI': None,
         'OLP': None,
         'country': 'Andorra',
         'country_code': 'AND'},
 'ARA': {'DP': 0.8,
         'EI': 0.68,
         'IND': 0.38,
         'LCS': 0.34,
         'OGI': 0.53,
         'OLP': 0.23,
         'country': 'Arab countries',
         'country_code': 'ARA'},
 'ARG': {'DP': 0.49,
         'EI': 0.86,
         'IND': 0.46,
         'LCS': 0.62,
         'OGI': 0.56,
         'OLP': 0.2,
         'country': 'Argentina',
         'country_code': 'ARG'},
 'ARM': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': None,
         'OGI': None,
         'OLP': 0.61,
         'country': 'Armenia',
         'country_code': 'ARM'},
 'AUL': {'DP': 0.38,
         'EI': 0.51,
         'IND': 0.9,
         'LCS': 0.71,
         'OGI': 0.61,
         'OLP': 0.21,
         'country': 'Australia',
         'country_code': 'AUL'},
 'AUT': {'DP': 0.11,
         'EI': 0.7,
         'IND': 0.55,
         'LCS': 0.63,
         'OGI': 0.79,
         'OLP': 0.6,
         'country': 'Austria',
         'country_code': 'AUT'},
 'AZE': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.22,
         'OGI': None,
         'OLP': 0.61,
         'country': 'Azerbaijan',
         'country_code': 'AZE'},
 'BAN': {'DP': 0.8,
         'EI': 0.6,
         'IND': 0.2,
         'LCS': 0.2,
         'OGI': 0.55,
         'OLP': 0.47,
         'country': 'Bangladesh',
         'country_code': 'BAN'},
 'BEF': {'DP': 0.67,
         'EI': 0.93,
         'IND': 0.72,
         'LCS': None,
         'OGI': 0.6,
         'OLP': None,
         'country': 'Belgium French',
         'country_code': 'BEF'},
 'BEL': {'DP': 0.65,
         'EI': 0.94,
         'IND': 0.75,
         'LCS': 0.57,
         'OGI': 0.54,
         'OLP': 0.82,
         'country': 'Belgium',
         'country_code': 'BEL'},
 'BEN': {'DP': 0.61,
         'EI': 0.97,
         'IND': 0.78,
         'LCS': None,
         'OGI': 0.43,
         'OLP': None,
         'country': 'Belgium Netherl',
         'country_code': 'BEN'},
 'BLR': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.15,
         'OGI': None,
         'OLP': 0.81,
         'country': 'Belarus',
         'country_code': 'BLR'},
 'BOS': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.44,
         'OGI': None,
         'OLP': 0.7,
         'country': 'Bosnia',
         'country_code': 'BOS'},
 'BRA': {'DP': 0.69,
         'EI': 0.76,
         'IND': 0.38,
         'LCS': 0.59,
         'OGI': 0.49,
         'OLP': 0.44,
         'country': 'Brazil',
         'country_code': 'BRA'},
 'BUF': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.18,
         'OGI': None,
         'OLP': 0.27,
         'country': 'Burkina Faso',
         'country_code': 'BUF'},
 'BUL': {'DP': 0.7,
         'EI': 0.85,
         'IND': 0.3,
         'LCS': 0.16,
         'OGI': 0.4,
         'OLP': 0.69,
         'country': 'Bulgaria',
         'country_code': 'BUL'},
 'CAF': {'DP': 0.54,
         'EI': 0.6,
         'IND': 0.73,
         'LCS': None,
         'OGI': 0.45,
         'OLP': None,
         'country': 'Canada French',
         'country_code': 'CAF'},
 'CAN': {'DP': 0.39,
         'EI': 0.48,
         'IND': 0.8,
         'LCS': 0.68,
         'OGI': 0.52,
         'OLP': 0.36,
         'country': 'Canada',
         'country_code': 'CAN'},
 'CHI': {'DP': 0.8,
         'EI': 0.3,
         'IND': 0.2,
         'LCS': 0.24,
         'OGI': 0.66,
         'OLP': 0.87,
         'country': 'China',
         'country_code': 'CHI'},
 'CHL': {'DP': 0.63,
         'EI': 0.86,
         'IND': 0.23,
         'LCS': 0.68,
         'OGI': 0.28,
         'OLP': 0.31,
         'country': 'Chile',
         'country_code': 'CHL'},
 'COL': {'DP': 0.67,
         'EI': 0.8,
         'IND': 0.13,
         'LCS': 0.83,
         'OGI': 0.64,
         'OLP': 0.13,
         'country': 'Colombia',
         'country_code': 'COL'},
 'COS': {'DP': 0.35,
         'EI': 0.86,
         'IND': 0.15,
         'LCS': None,
         'OGI': 0.21,
         'OLP': None,
         'country': 'Costa Rica',
         'country_code': 'COS'},
 'CRO': {'DP': 0.73,
         'EI': 0.8,
         'IND': 0.33,
         'LCS': 0.33,
         'OGI': 0.4,
         'OLP': 0.58,
         'country': 'Croatia',
         'country_code': 'CRO'},
 'CYP': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.7,
         'OGI': None,
         'OLP': None,
         'country': 'Cyprus',
         'country_code': 'CYP'},
 'CZE': {'DP': 0.57,
         'EI': 0.74,
         'IND': 0.58,
         'LCS': 0.29,
         'OGI': 0.57,
         'OLP': 0.7,
         'country': 'Czech Rep',
         'country_code': 'CZE'},
 'DEN': {'DP': 0.18,
         'EI': 0.23,
         'IND': 0.74,
         'LCS': 0.7,
         'OGI': 0.16,
         'OLP': 0.35,
         'country': 'Denmark',
         'country_code': 'DEN'},
 'DOM': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.54,
         'OGI': None,
         'OLP': 0.13,
         'country': 'Dominican Rep',
         'country_code': 'DOM'},
 'ECA': {'DP': 0.78,
         'EI': 0.67,
         'IND': 0.08,
         'LCS': None,
         'OGI': 0.63,
         'OLP': None,
         'country': 'Ecuador',
         'country_code': 'ECA'},
 'EGY': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.04,
         'OGI': None,
         'OLP': 0.07,
         'country': 'Egypt',
         'country_code': 'EGY'},
 'EST': {'DP': 0.4,
         'EI': 0.6,
         'IND': 0.6,
         'LCS': 0.16,
         'OGI': 0.3,
         'OLP': 0.82,
         'country': 'Estonia',
         'country_code': 'EST'},
 'ETH': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.46,
         'OGI': None,
         'OLP': None,
         'country': 'Ethiopia',
         'country_code': 'ETH'},
 'FIN': {'DP': 0.33,
         'EI': 0.59,
         'IND': 0.63,
         'LCS': 0.57,
         'OGI': 0.26,
         'OLP': 0.38,
         'country': 'Finland',
         'country_code': 'FIN'},
 'FRA': {'DP': 0.68,
         'EI': 0.86,
         'IND': 0.71,
         'LCS': 0.48,
         'OGI': 0.43,
         'OLP': 0.63,
         'country': 'France',
         'country_code': 'FRA'},
 'GBR': {'DP': 0.35,
         'EI': 0.35,
         'IND': 0.89,
         'LCS': 0.69,
         'OGI': 0.66,
         'OLP': 0.51,
         'country': 'Great Britain',
         'country_code': 'GBR'},
 'GEE': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.34,
         'OGI': None,
         'OLP': 0.78,
         'country': 'Germany East',
         'country_code': 'GEE'},
 'GEO': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.32,
         'OGI': None,
         'OLP': 0.38,
         'country': 'Georgia',
         'country_code': 'GEO'},
 'GER': {'DP': 0.35,
         'EI': 0.65,
         'IND': 0.67,
         'LCS': 0.4,
         'OGI': 0.66,
         'OLP': 0.83,
         'country': 'Germany',
         'country_code': 'GER'},
 'GHA': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.72,
         'OGI': None,
         'OLP': 0.04,
         'country': 'Ghana',
         'country_code': 'GHA'},
 'GRE': {'DP': 0.6,
         'EI': 1.12,
         'IND': 0.35,
         'LCS': 0.5,
         'OGI': 0.57,
         'OLP': 0.45,
         'country': 'Greece',
         'country_code': 'GRE'},
 'GUA': {'DP': 0.95,
         'EI': 1.01,
         'IND': 0.06,
         'LCS': None,
         'OGI': 0.37,
         'OLP': None,
         'country': 'Guatemala',
         'country_code': 'GUA'},
 'HOK': {'DP': 0.68,
         'EI': 0.29,
         'IND': 0.25,
         'LCS': 0.17,
         'OGI': 0.57,
         'OLP': 0.61,
         'country': 'Hong Kong',
         'country_code': 'HOK'},
 'HUN': {'DP': 0.46,
         'EI': 0.82,
         'IND': 0.8,
         'LCS': 0.31,
         'OGI': 0.88,
         'OLP': 0.58,
         'country': 'Hungary',
         'country_code': 'HUN'},
 'ICE': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.67,
         'OGI': None,
         'OLP': 0.28,
         'country': 'Iceland',
         'country_code': 'ICE'},
 'IDO': {'DP': 0.78,
         'EI': 0.48,
         'IND': 0.14,
         'LCS': 0.38,
         'OGI': 0.46,
         'OLP': 0.62,
         'country': 'Indonesia',
         'country_code': 'IDO'},
 'IND': {'DP': 0.77,
         'EI': 0.4,
         'IND': 0.48,
         'LCS': 0.26,
         'OGI': 0.56,
         'OLP': 0.51,
         'country': 'India',
         'country_code': 'IND'},
 'IRA': {'DP': 0.58,
         'EI': 0.59,
         'IND': 0.41,
         'LCS': 0.4,
         'OGI': 0.43,
         'OLP': 0.14,
         'country': 'Iran',
         'country_code': 'IRA'},
 'IRE': {'DP': 0.28,
         'EI': 0.35,
         'IND': 0.7,
         'LCS': 0.65,
         'OGI': 0.68,
         'OLP': 0.24,
         'country': 'Ireland',
         'country_code': 'IRE'},
 'IRQ': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.17,
         'OGI': None,
         'OLP': 0.25,
         'country': 'Iraq',
         'country_code': 'IRQ'},
 'ISR': {'DP': 0.13,
         'EI': 0.81,
         'IND': 0.54,
         'LCS': None,
         'OGI': 0.47,
         'OLP': 0.38,
         'country': 'Israel',
         'country_code': 'ISR'},
 'ITA': {'DP': 0.5,
         'EI': 0.75,
         'IND': 0.76,
         'LCS': 0.3,
         'OGI': 0.7,
         'OLP': 0.61,
         'country': 'Italy',
         'country_code': 'ITA'},
 'JAM': {'DP': 0.45,
         'EI': 0.13,
         'IND': 0.39,
         'LCS': None,
         'OGI': 0.68,
         'OLP': None,
         'country': 'Jamaica',
         'country_code': 'JAM'},
 'JOR': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.43,
         'OGI': None,
         'OLP': 0.16,
         'country': 'Jordan',
         'country_code': 'JOR'},
 'JPN': {'DP': 0.54,
         'EI': 0.92,
         'IND': 0.46,
         'LCS': 0.42,
         'OGI': 0.95,
         'OLP': 0.88,
         'country': 'Japan',
         'country_code': 'JPN'},
 'KOR': {'DP': 0.6,
         'EI': 0.85,
         'IND': 0.18,
         'LCS': 0.29,
         'OGI': 0.39,
         'OLP': 1.0,
         'country': 'Korea South',
         'country_code': 'KOR'},
 'KYR': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.39,
         'OGI': None,
         'OLP': 0.66,
         'country': 'Kyrgyz Rep',
         'country_code': 'KYR'},
 'LAT': {'DP': 0.44,
         'EI': 0.63,
         'IND': 0.7,
         'LCS': 0.13,
         'OGI': 0.09,
         'OLP': 0.69,
         'country': 'Latvia',
         'country_code': 'LAT'},
 'LIT': {'DP': 0.42,
         'EI': 0.65,
         'IND': 0.6,
         'LCS': 0.16,
         'OGI': 0.19,
         'OLP': 0.82,
         'country': 'Lithuania',
         'country_code': 'LIT'},
 'LUX': {'DP': 0.4,
         'EI': 0.7,
         'IND': 0.6,
         'LCS': 0.56,
         'OGI': 0.5,
         'OLP': 0.64,
         'country': 'Luxembourg',
         'country_code': 'LUX'},
 'MAC': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.35,
         'OGI': None,
         'OLP': 0.62,
         'country': 'Macedonia Rep',
         'country_code': 'MAC'},
 'MAL': {'DP': 1.04,
         'EI': 0.36,
         'IND': 0.26,
         'LCS': 0.57,
         'OGI': 0.5,
         'OLP': 0.41,
         'country': 'Malaysia',
         'country_code': 'MAL'},
 'MEX': {'DP': 0.81,
         'EI': 0.82,
         'IND': 0.3,
         'LCS': 0.97,
         'OGI': 0.69,
         'OLP': 0.24,
         'country': 'Mexico',
         'country_code': 'MEX'},
 'MLI': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.43,
         'OGI': None,
         'OLP': 0.2,
         'country': 'Mali',
         'country_code': 'MLI'},
 'MLT': {'DP': 0.56,
         'EI': 0.96,
         'IND': 0.59,
         'LCS': 0.66,
         'OGI': 0.47,
         'OLP': 0.47,
         'country': 'Malta',
         'country_code': 'MLT'},
 'MNG': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.2,
         'OGI': None,
         'OLP': 0.75,
         'country': 'Montenegro',
         'country_code': 'MNG'},
 'MOL': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.19,
         'OGI': None,
         'OLP': 0.71,
         'country': 'Moldova',
         'country_code': 'MOL'},
 'MOR': {'DP': 0.7,
         'EI': 0.68,
         'IND': 0.46,
         'LCS': 0.25,
         'OGI': 0.53,
         'OLP': 0.14,
         'country': 'Morocco',
         'country_code': 'MOR'},
 'NET': {'DP': 0.38,
         'EI': 0.53,
         'IND': 0.8,
         'LCS': 0.68,
         'OGI': 0.14,
         'OLP': 0.67,
         'country': 'Netherlands',
         'country_code': 'NET'},
 'NIG': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.84,
         'OGI': None,
         'OLP': 0.13,
         'country': 'Nigeria',
         'country_code': 'NIG'},
 'NOR': {'DP': 0.31,
         'EI': 0.5,
         'IND': 0.69,
         'LCS': 0.55,
         'OGI': 0.08,
         'OLP': 0.35,
         'country': 'Norway',
         'country_code': 'NOR'},
 'NZL': {'DP': 0.22,
         'EI': 0.49,
         'IND': 0.79,
         'LCS': 0.75,
         'OGI': 0.58,
         'OLP': 0.33,
         'country': 'New Zealand',
         'country_code': 'NZL'},
 'PAK': {'DP': 0.55,
         'EI': 0.7,
         'IND': 0.14,
         'LCS': 0.0,
         'OGI': 0.5,
         'OLP': 0.5,
         'country': 'Pakistan',
         'country_code': 'PAK'},
 'PAN': {'DP': 0.95,
         'EI': 0.86,
         'IND': 0.11,
         'LCS': None,
         'OGI': 0.44,
         'OLP': None,
         'country': 'Panama',
         'country_code': 'PAN'},
 'PER': {'DP': 0.64,
         'EI': 0.87,
         'IND': 0.16,
         'LCS': 0.46,
         'OGI': 0.42,
         'OLP': 0.25,
         'country': 'Peru',
         'country_code': 'PER'},
 'PHI': {'DP': 0.94,
         'EI': 0.44,
         'IND': 0.32,
         'LCS': 0.42,
         'OGI': 0.64,
         'OLP': 0.27,
         'country': 'Philippines',
         'country_code': 'PHI'},
 'POL': {'DP': 0.68,
         'EI': 0.93,
         'IND': 0.6,
         'LCS': 0.29,
         'OGI': 0.64,
         'OLP': 0.38,
         'country': 'Poland',
         'country_code': 'POL'},
 'POR': {'DP': 0.63,
         'EI': 1.04,
         'IND': 0.27,
         'LCS': 0.33,
         'OGI': 0.31,
         'OLP': 0.28,
         'country': 'Portugal',
         'country_code': 'POR'},
 'PUE': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.9,
         'OGI': None,
         'OLP': 0.0,
         'country': 'Puerto Rico',
         'country_code': 'PUE'},
 'ROM': {'DP': 0.9,
         'EI': 0.9,
         'IND': 0.3,
         'LCS': 0.2,
         'OGI': 0.42,
         'OLP': 0.52,
         'country': 'Romania',
         'country_code': 'ROM'},
 'RUS': {'DP': 0.93,
         'EI': 0.95,
         'IND': 0.39,
         'LCS': 0.2,
         'OGI': 0.36,
         'OLP': 0.81,
         'country': 'Russia',
         'country_code': 'RUS'},
 'RWA': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.37,
         'OGI': None,
         'OLP': 0.18,
         'country': 'Rwanda',
         'country_code': 'RWA'},
 'SAF': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.63,
         'OGI': None,
         'OLP': 0.34,
         'country': 'South Africa',
         'country_code': 'SAF'},
 'SAL': {'DP': 0.66,
         'EI': 0.94,
         'IND': 0.19,
         'LCS': 0.89,
         'OGI': 0.4,
         'OLP': 0.2,
         'country': 'El Salvador',
         'country_code': 'SAL'},
 'SAU': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.52,
         'OGI': None,
         'OLP': 0.36,
         'country': 'Saudi Arabia',
         'country_code': 'SAU'},
 'SAW': {'DP': 0.49,
         'EI': 0.49,
         'IND': 0.65,
         'LCS': None,
         'OGI': 0.63,
         'OLP': None,
         'country': 'South Africa white',
         'country_code': 'SAW'},
 'SER': {'DP': 0.86,
         'EI': 0.92,
         'IND': 0.25,
         'LCS': 0.28,
         'OGI': 0.43,
         'OLP': 0.52,
         'country': 'Serbia',
         'country_code': 'SER'},
 'SIN': {'DP': 0.74,
         'EI': 0.08,
         'IND': 0.2,
         'LCS': 0.46,
         'OGI': 0.48,
         'OLP': 0.72,
         'country': 'Singapore',
         'country_code': 'SIN'},
 'SLK': {'DP': 1.04,
         'EI': 0.51,
         'IND': 0.52,
         'LCS': 0.28,
         'OGI': 1.1,
         'OLP': 0.77,
         'country': 'Slovak Rep',
         'country_code': 'SLK'},
 'SLV': {'DP': 0.71,
         'EI': 0.88,
         'IND': 0.27,
         'LCS': 0.48,
         'OGI': 0.19,
         'OLP': 0.49,
         'country': 'Slovenia',
         'country_code': 'SLV'},
 'SPA': {'DP': 0.57,
         'EI': 0.86,
         'IND': 0.51,
         'LCS': 0.44,
         'OGI': 0.42,
         'OLP': 0.48,
         'country': 'Spain',
         'country_code': 'SPA'},
 'SUR': {'DP': 0.85,
         'EI': 0.92,
         'IND': 0.47,
         'LCS': None,
         'OGI': 0.37,
         'OLP': None,
         'country': 'Suriname',
         'country_code': 'SUR'},
 'SWE': {'DP': 0.31,
         'EI': 0.29,
         'IND': 0.71,
         'LCS': 0.78,
         'OGI': 0.05,
         'OLP': 0.53,
         'country': 'Sweden',
         'country_code': 'SWE'},
 'SWF': {'DP': 0.7,
         'EI': 0.7,
         'IND': 0.64,
         'LCS': None,
         'OGI': 0.58,
         'OLP': None,
         'country': 'Switzerland French',
         'country_code': 'SWF'},
 'SWG': {'DP': 0.26,
         'EI': 0.56,
         'IND': 0.69,
         'LCS': None,
         'OGI': 0.72,
         'OLP': None,
         'country': 'Switzerland German',
         'country_code': 'SWG'},
 'SWI': {'DP': 0.34,
         'EI': 0.58,
         'IND': 0.68,
         'LCS': 0.66,
         'OGI': 0.7,
         'OLP': 0.74,
         'country': 'Switzerland',
         'country_code': 'SWI'},
 'TAI': {'DP': 0.58,
         'EI': 0.69,
         'IND': 0.17,
         'LCS': 0.49,
         'OGI': 0.45,
         'OLP': 0.93,
         'country': 'Taiwan',
         'country_code': 'TAI'},
 'TAN': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.38,
         'OGI': None,
         'OLP': 0.34,
         'country': 'Tanzania',
         'country_code': 'TAN'},
 'THA': {'DP': 0.64,
         'EI': 0.64,
         'IND': 0.2,
         'LCS': 0.45,
         'OGI': 0.34,
         'OLP': 0.32,
         'country': 'Thailand',
         'country_code': 'THA'},
 'TRI': {'DP': 0.47,
         'EI': 0.55,
         'IND': 0.16,
         'LCS': 0.8,
         'OGI': 0.58,
         'OLP': 0.13,
         'country': 'Trinidad and Tobago',
         'country_code': 'TRI'},
 'TUR': {'DP': 0.66,
         'EI': 0.85,
         'IND': 0.37,
         'LCS': 0.49,
         'OGI': 0.45,
         'OLP': 0.46,
         'country': 'Turkey',
         'country_code': 'TUR'},
 'UGA': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.52,
         'OGI': None,
         'OLP': 0.24,
         'country': 'Uganda',
         'country_code': 'UGA'},
 'UKR': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.14,
         'OGI': None,
         'OLP': 0.86,
         'country': 'Ukraine',
         'country_code': 'UKR'},
 'URU': {'DP': 0.61,
         'EI': 1.0,
         'IND': 0.36,
         'LCS': 0.53,
         'OGI': 0.38,
         'OLP': 0.26,
         'country': 'Uruguay',
         'country_code': 'URU'},
 'USA': {'DP': 0.4,
         'EI': 0.46,
         'IND': 0.91,
         'LCS': 0.68,
         'OGI': 0.62,
         'OLP': 0.26,
         'country': 'U.S.A.',
         'country_code': 'USA'},
 'VEN': {'DP': 0.81,
         'EI': 0.76,
         'IND': 0.12,
         'LCS': 1.0,
         'OGI': 0.73,
         'OLP': 0.16,
         'country': 'Venezuela',
         'country_code': 'VEN'},
 'VIE': {'DP': 0.7,
         'EI': 0.3,
         'IND': 0.2,
         'LCS': 0.35,
         'OGI': 0.4,
         'OLP': 0.57,
         'country': 'Vietnam',
         'country_code': 'VIE'},
 'ZAM': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.42,
         'OGI': None,
         'OLP': 0.3,
         'country': 'Zambia',
         'country_code': 'ZAM'},
 'ZIM': {'DP': None,
         'EI': None,
         'IND': None,
         'LCS': 0.28,
         'OGI': None,
         'OLP': 0.15,
         'country': 'Zimbabwe',
         'country_code': 'ZIM'}}

COUNTRY_ALIASES = {'ES': 'SPA',
 'ESPAÑA': 'SPA',
 'GB': 'GBR',
 'GREAT BRITAIN': 'GBR',
 'JAPAN': 'JPN',
 'JP': 'JPN',
 'MEXICO': 'MEX',
 'MX': 'MEX',
 'SPAIN': 'SPA',
 'U.S.A.': 'USA',
 'UK': 'GBR',
 'UNITED KINGDOM': 'GBR',
 'UNITED STATES': 'USA',
 'UNITED STATES OF AMERICA': 'USA',
 'US': 'USA'}


def _build_country_lookup():
    lookup = {}

    for code, profile in HOFSTEDE.items():
        lookup[_normalize_key(code)] = code
        lookup[_normalize_key(profile.get("country"))] = code

    for alias, code in COUNTRY_ALIASES.items():
        if code in HOFSTEDE:
            lookup[_normalize_key(alias)] = code

    return lookup


COUNTRY_LOOKUP = _build_country_lookup()


def normalize_country_code(value):
    key = _normalize_key(value)
    return COUNTRY_LOOKUP.get(key)


def get_country_profile(value):
    code = normalize_country_code(value)

    if not code:
        return None

    return HOFSTEDE.get(code)


def get_dimension_value(profile, dimension, default=0):
    value = profile.get(dimension) if isinstance(profile, dict) else None

    if value is None:
        return default

    return value


def comparable_dimensions(source, target):
    return [
        dimension
        for dimension in CULTURAL_DIMENSIONS
        if get_dimension_value(source, dimension, None) is not None
        and get_dimension_value(target, dimension, None) is not None
    ]
